### ISSUE TITLE
Sharing a preset fitting to a friend contact breaks

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#154]
Make a preset fitting.
Add a friend
Share to friend.
Bad things happen.

**Comment by Doc-Saintly** [comment]
The sender crashes when clicking the "send" button. The crash dump says `The thread tried to read from or write to a virtual address for which it does not have the appropriate access.`

It appears to be purely client side, since no requests (not even any packets) are sent from the client before it crashes.
