### ISSUE TITLE
Empty loot on lootsplitter throws exception

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#213]
Handle the empty case there bud.
_(Generally not a problem as loot-splitting bosses usually have a full loot table, but this is a general robustness issue)_

**Comment by MikeJeffers** [comment]
https://github.com/OpenPerpetuum/PerpetuumServer/blob/Development/src/Perpetuum/Services/Looting/LootGenerator.cs#L12
set to an empty collection instead of null :)

**Comment by Veritania** [comment]
Hello! I've opened [PR-280](https://github.com/OpenPerpetuum/PerpetuumServer/pull/280) to try and target this issue.

[LootGenerator.cs L14-L17](https://github.com/Veritania/PerpetuumServer/blob/f30f0d1413fffdc591074b8485a85d97bfaed97e/src/Perpetuum/Services/Looting/LootGenerator.cs#L14-L17).
Regarding robustness, would it make sense to also check for null on the `<LootGeneratorItemInfo> lootInfos` parameter when we create a LootGenerator instance?

I ask because I'm unsure if it could ever be given a null value which could then overwrite the empty list, and set `_lootInfos` to null anyway.

**Comment by MikeJeffers** [comment]
That *could* happen, tracing references to the constructor show that most are pretty good about passing an empty array instead of null.  But for robustness I agree a null check might be worth it due to how this class might be created in various and increasingly complex ways - it would for example be *very easy* to forget that passing null instead of an empty array is a breaking case.
