### ISSUE TITLE
Dev-only mode

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#257]
Allow the server to bootup in "dev only" mode to only let tooladmin level accounts in.
The client used to show if the server was in this state after the client connects before the client logs in.  I don't know if that works with the server selection now.  But this may indicate the existence of some code/feature we can wire up again.

Some desired functionality:
- Ideally its a mode we can toggle at runtime or on startup.
- A startup arg (or config file value) to have it start in dev-only state, or not.
- A command to enable/disable this state.

Why?
Even though we catch most things in dev/staging, it won't catch everything.
It would be good to have a period where admins can verify the integrity of a live server update before players jump on, giving us a chance to rollback without reversing any player progress.

**Comment by Veritania** [comment]
Did a little late-night investigation, it is mostly speculation on my part, but here's some interesting pieces I found:

https://github.com/OpenPerpetuum/PerpetuumServer/blob/66e678d0bedade47d0278c40aeba1ef492e4c1a4/src/Perpetuum/Services/Relay/RelayState.cs#L6-L10

This is interesting, because our `SignInRequestHandler.cs` has the following check as one of the first things before we put the player in queue to login.

https://github.com/OpenPerpetuum/PerpetuumServer/blob/66e678d0bedade47d0278c40aeba1ef492e4c1a4/src/Perpetuum.RequestHandlers/SignInRequestHandler.cs#L31-L34

So I think we can configure these values to only allow accounts with a certain `AccessLevel` to log on to the service

https://github.com/OpenPerpetuum/PerpetuumServer/blob/66e678d0bedade47d0278c40aeba1ef492e4c1a4/src/Perpetuum/AccessLevel.cs#L18-L28

And then manage the state via these requests, to open/close the server to the public
https://github.com/OpenPerpetuum/PerpetuumServer/blob/66e678d0bedade47d0278c40aeba1ef492e4c1a4/src/Perpetuum.RequestHandlers/RelayClose.cs#L15-L17
https://github.com/OpenPerpetuum/PerpetuumServer/blob/66e678d0bedade47d0278c40aeba1ef492e4c1a4/src/Perpetuum.RequestHandlers/RelayOpen.cs#L15-L17

I haven't seen anything (yet) that would indicate a server showing up as available but in "dev-only" mode.

**Comment by MikeJeffers** [comment]
I think this is exactly what we were looking for! Great documentation

**Comment by Veritania** [comment]
#290 Allows admins to flip the state of a Relay between Open/Closed for regular players, while the server is running.

We are still missing the feature of being able to start-up the server in this "Closed" mode.

**Comment by Veritania** [comment]
After PR #290 and PR #297, we will have a config value in `perpetuum.ini` which will define if the server should start-up as Open for the public, or Closed to the public => Meaning only admin accounts can connect to it.

Regular players will be met with a pop-up `err_RelayIsClosedForPublic` when trying to login to the server

This state can then be changed during runtime via ingame  admin chat commands.


> The client used to show if the server was in this state after the client connects before the client logs in. I don't know if that works with the server selection now. 

I haven't found anything that indicates this feature on the serverlist.

**Comment by MikeJeffers** [comment]
> I haven't found anything that indicates this feature on the serverlist.

Not server list, it was something that would appear as a warning when the client connected to the (official) server in this mode.  It might not be functional anymore since they didn't foresee its use on player made servers.
