### ISSUE TITLE
Weather jump

### ISSUE THREAD

**Issue by aqpanaciy** [OpenPerpetuum/PerpetuumServer#460]
I have noticed sharp changes in weather special effects when playing on the online server. It seems to be related to the maximum value (255) of the weather. Here is a comparison [video](https://youtu.be/y4riBUGuUQ0) of weather changes from 254 to 255 and from 0 to 254 when tested on a local server.

This is a [video](https://youtu.be/yQN6PGwYjLQ) with a weather jump on an online server.

I propose [here](https://github.com/OpenPerpetuum/PerpetuumServer/blob/Development/src/Perpetuum/Services/Weather/WeatherService.cs?plain=1#L21) to limit the maximum value to 254.

**Comment by MikeJeffers** [comment]
Thank you for supplying video and logs with the issue, super informative and help others replicate!
I did notice this too and debated clamping the weather bit to 254 to avoid this issue.. but we determined at the time it was really a client issue rather than the server - but given that was reported a while ago, maybe better to workaround it server side at this point.

Thank you for reporting!

**Comment by aqpanaciy** [comment]
Limiting the max value to 254 fixes the weather jumping issue, but reduces the chance of clear weather.
